name: build-push
on:
  pull_request:
    paths:
      - Dockerfile
      - app.py
      - requirements.txt
      - .github/workflows/build.yaml
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - app.py
      - requirements.txt
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
    outputs:
      # Add output with tags to pass to different sequential jobs below
      tags: ${{ steps.export.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Log in to the Container registry
        uses: docker/login-action@327cd5a69de6c009b9ce71bce8395f28e651bf99
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # initially https://github.com/actions/runner/issues/1039#issuecomment-895908863
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo "tags=${{ steps.meta.outputs.tags }}-${{ github.sha }}" >> $GITHUB_OUTPUT
        id: export
        name: Export tag

      - name: Test image
        run: |
          set -exu

          container_id=$(docker run -p 8080:8080 -d ${{ steps.meta.outputs.tags }}-${{ github.sha }} bash -c "python app.py run -h 0.0.0.0")
          docker ps
          while [ "$(docker inspect -f '{{.State.Status}}' "$container_id")" != "running" ]; do
            sleep 1
          done
          sleep 3
          set +x
          exec > >(tee /tmp/output.txt) 2>&1
          echo "## Output from CI:"
          echo "\`\`\`"
          set -v
          curl --fail http://localhost:8080
          curl --fail http://localhost:8080/foobar
          set +v
          echo "\`\`\`"

      - name: comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          file-path: /tmp/output.txt
          comment-tag: "ci"
